---
  - hosts: deploy_servers
    become: true
    tasks:
     - name: clone the git repo
       shell: git clone https://github.com/iliassanati/student-list.git

     - name: Execute the docker-compose file
       docker_compose:
         project_src: /student-list

  
