---
- hosts: deploy_servers
  become: true
  tasks:
    - name: clone the git repo
      shell: git clone https://github.com/iliassanati/student-list.git

    - name: Go to the placement of the dokcer-compose.yml
      shell: cd student-list

    # docker network
    - name: crete docker network to interconnect containers
      docker_network:
        name: student-list_network

    # deploy API

    - name: Deploy api
      docker_container:
        name: api
        image: registry.local.com:5000/iliassanati/simple_api:v1
        volumes:
          - ./simple_api/student_age.json:/data/student_age.json
        ports:
          - 5000:5000
        networks:
          - name: student-list_network

    # deploy frontend

    - name: Deploy frontend
      docker_container:
        name: website
        image: php:7.2-apache
        depends_on:
          - api
        volumes:
          - ./website:/var/www/html
        env:
          USERNAME: 'toto'
          PASSWORD: 'python'
        ports:
          - '80:80'
        networks:
          - name: student-list_network
